apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: intel-rmd-operator
roleRef:
  kind: ClusterRole
  name: intel-rmd-operator 
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: default 
  name: intel-rmd-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: intel-rmd-node-agent
roleRef:
  kind: ClusterRole
  name: intel-rmd-node-agent 
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: default 
  name: intel-rmd-node-agent
