kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: intel-rmd-operator
subjects:
- kind: ServiceAccount
  name: intel-rmd-operator
roleRef:
  kind: Role
  name: intel-rmd-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: intel-rmd-node-agent
subjects:
- kind: ServiceAccount
  name: intel-rmd-node-agent
roleRef:
  kind: Role
  name: intel-rmd-node-agent
  apiGroup: rbac.authorization.k8s.io
