apiVersion: intel.com/v1alpha1
kind: RmdWorkload
metadata:
  name: rmdworkload-guaranteed-3
spec:
  # Add fields here
  coreIds: ["41-44"]
  rdt:
    cache:
      max: 1
      min: 1
  nodes: ["silpixa00400471"] 
